version: '3'
services: 
  xrayr: 
    image: crackair/xrayr:latest
    volumes:
      - ./config.yml:/etc/XrayR/config.yml # 映射配置文件夹
      - ./dns.json:/etc/XrayR/dns.json 
    restart: always
    network_mode: host
